### ISSUE TITLE
Распаковка blk из Enlisted\CRSED

### ISSUE THREAD

**Issue by Viz-Allati** [kotiq/wt-tools#1]
Enlisted и CRSED это две другие игры под издательством Gaijin, так же на движке Dagor Engine. Соответственно формат blk там используется примерно тот же, что и в War Thunder. Однако при распаковке возникают ошибки, например следующего рода:

> D:\Soft\DataMining\blk-master\tests\demo>blk_unpack_demo.py ../../../e_ww2_common.vromfs.bin_u
...
../../../e_ww2_common.vromfs.bin_u\gamedata\items\avs_36_bayonet.blk
    Unknown file format
...
../../../e_ww2_common.vromfs.bin_u\gamedata\templates\base_soldier.blk
Traceback (most recent call last):
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 160, in <module>
    main()
  File "D:\Soft\Python3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Soft\Python3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Soft\Python3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Soft\Python3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 156, in main
    process_dir(path, out_type, is_sorted)
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 132, in process_dir
    process_dir(entry.path, out_type, is_sorted)
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 132, in process_dir
    process_dir(entry.path, out_type, is_sorted)
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 134, in process_dir
    process_file(entry.path, None, out_type, is_sorted)
  File "D:\Soft\DataMining\blk-master\tests\demo\blk_unpack_demo.py", line 91, in process_file
    root = bin.compose_fat(istream)
  File "D:\Soft\DataMining\blk-master\src\blk\binary\constructor.py", line 277, in compose_fat
    return FileAdapter(FileStruct, names).parse_stream(istream)
  File "D:\Soft\Python3\lib\site-packages\construct\core.py", line 313, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "D:\Soft\Python3\lib\site-packages\construct\core.py", line 325, in _parsereport
    obj = self._parse(stream, context, path)
  File "D:\Soft\Python3\lib\site-packages\construct\core.py", line 710, in _parse
    return self._decode(obj, context, path)
  File "D:\Soft\DataMining\blk-master\src\blk\binary\constructor.py", line 151, in _decode
    name = names[name_id]
IndexError: list index out of range

Версия Python 3.8.10, под Windows. Версия blk_unpack_demo.py (и остального) от 16 августа. Проверил на относительно свежем aces.vromfs.bin из WT - blk распаковались нормально, так что пока что предполагаю, что причина не в том, что я накосячил при установке инструментария. До всей этой заварухи со сменой формата WT Tools работал нормально с файлами из этих игр. Прикладываю примеры сбоящих blk и исходного vromfs.bin из Enlisted.
[sample files.zip](https://github.com/kotiq/blk/files/7013544/sample.files.zip)

**Comment by kotiq** [comment]
Добавил значение для генератора в случае пустого файла.

**Comment by Viz-Allati** [comment]
Ещё раз спасибо, всё работает.
