### ISSUE TITLE
zstd.ZstdError: decompression error: Dictionary mismatch on WT 2.21 vroms

### ISSUE THREAD

**Issue by L-Mustang** [kotiq/wt-tools#12]
An exception is thrown when trying to extract a vromfs.bin archive for version 2.21 of War Thunder.

Full stacktrace:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "src/wt_tools/vromfs_unpacker.py", line 203, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 829, in __call__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 782, in main
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 1066, in invoke
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 610, in invoke
  File "src/wt_tools/vromfs_unpacker.py", line 199, in main
  File "src/wt_tools/vromfs_unpacker.py", line 131, in unpack
zstd.ZstdError: decompression error: Dictionary mismatch
```

I've attached a sample vroms of version 2.21.0.14.

[aces.vromfs.bin.zip](https://github.com/kotiq/wt-tools/files/9873540/aces.vromfs.bin.zip)

**Comment by kotiq** [comment]
It seems to unpack normally for me.
```sh
git rev-parse --short HEAD
c343b01
```

```sh
python -m wt_tools.vromfs_unpacker aces.vromfs.bin 
Unpacking files  [####################################]  100%
[OK] /tmp/iss12/aces.vromfs.bin => /tmp/iss12/aces.vromfs.bin_u
```

**Comment by L-Mustang** [comment]
Does it also work for you with the latest compiled release?
https://github.com/kotiq/wt-tools/releases/tag/v0.2.2.9

I'm using the compiled version, I forgot to mention that.

**Comment by kotiq** [comment]
Yes, for version 0.2.2.9 (commit e55dd41) the error is reproduced.

**Comment by L-Mustang** [comment]
Is it perhaps possible for you to build new binaries (and create a release) for commit c343b01?

**Comment by kotiq** [comment]
This is problematic to do now. I have found that I cannot officially download msvc compilers to test builds. Support for the Windows platform is therefore mutually suspended.

**Comment by kotiq** [comment]
I made a build for Windows for the current version.
[v0.2.2.10](https://github.com/kotiq/wt-tools/releases/tag/v0.2.2.10)

**Comment by L-Mustang** [comment]
The new version works, thanks!
